Sign up window
alirzaMhd/x_library pull request #2
Opened 2023-04-14 17:00 UTC by p0u74

A series of changes were made :

- Directory added for icon files
- Some variable names changed
- Improvement clean code

2023-04-14 17:03 UTC, alirzaMhd commented
make a main.py file and run those mentioned line in there...
next time dont overdo by removing a branch fix issues in same branch and open new pr

2023-04-14 18:44 UTC, alirzaMhd commented
1. Basic import

The simplest way to import a module or package is to use the import keyword. For example, if you have a file called my_module.py, you can import it like this:

import my_module
This makes the code and functions defined in my_module.py available in your current script.

2. Importing specific functions or classes

You can use the from ... import ... statement to import specific functions or classes from a module. For example, if my_module.py contains a function called my_function, you can import it like this:

from my_module import my_function
This allows you to use my_function directly in your script without needing to reference the module name.

3. Importing with an alias

You can use the as keyword to give an imported module or function an alias. This is useful when you want to avoid naming conflicts or make the imported names shorter and more convenient. For example:

import my_module as mm
from my_module import my_function as mf
Now you can use mm and mf as aliases for my_module and my_function, respectively.

4. Importing resources within packages using importlib.resources

importlib.resources allows you to access resources (such as files) within packages. This provides a more consistent way of dealing with files inside your packages and gives you easier access to resource files in other packages. For example, if you have a package structure like this:

books/
│
├── __init__.py
├── alice_in_wonderland.png
└── alice_in_wonderland.txt
You can use open_text() and open_binary() to open text and binary files, respectively:

from importlib import resources

with resources.open_text("books", "alice_in_wonderland.txt") as fid:
    alice = fid.readlines()

with resources.open_binary("books", "alice_in_wonderland.png") as fid:
    cover = fid.read()
[realpython.com](https://realpython.com/python-import/)

5. Adding a directory to sys.path

You can add a directory to the Python import path by modifying the sys.path list. This allows you to import modules from that directory. For example:

import sys
sys.path.append('PATH_TO_DIRECTORY')
Keep in mind that modifying sys.path can potentially cause issues if not done carefully.

[stackoverflow.com](https://stackoverflow.com/questions/15681366/importing-files-in-python)

6. Using __init__.py to make a directory behave like a module

By adding an __init__.py file (which can be empty) to a directory, you can make that directory behave like a module, allowing you to import files from it. This is a better approach than modifying sys.path.

[stackoverflow.com](https://stackoverflow.com/questions/15681366/importing-files-in-python)

Imports style guide

According to PEP 8, the Python style guide, you should organize imports into groups: first standard library imports, then third-party imports, and finally local application or library imports. This helps make your code more readable and maintainable.

[realpython.com](https://realpython.com/python-import/)

These are some of the most common ways to import files and packages in Python. There are more advanced techniques and customization options available in the Python import system, but these methods should cover most use cases.

2023-04-14 18:45 UTC, alirzaMhd requested changes

2023-04-14 18:45 UTC, alirzaMhd commented on sign_up_window.py
> +class Window(QWidget) :
SignUpWindow

2023-04-14 18:45 UTC, alirzaMhd commented on sign_up_window.py
> +app = QApplication(sys.argv)
bring that in main!!!!!!!

2023-04-14 18:45 UTC, alirzaMhd commented on sign_up_window.py
> +Window = Window()
bring these in main!!!!!!!

2023-04-15 00:15 UTC, p0u74 commented on sign_up_window.py
> +app = QApplication(sys.argv)
oh thanks it's helped

2023-04-15 00:56 UTC, p0u74 reviewed
thanks, changes submitted and main.py created.

2023-04-15 01:00 UTC, merged